### PR TITLE
Jasmine-auto-spies: Updated to use jasmine-core v5

### LINKED ISSUE #76: Make jasmine-auto-spies compatible with jasmine-core 5
**Is your feature request related to a problem? Please describe.**
_jasmine-auto-spies_ is not compatible with the current version of jasmine-core ([v5.x](https://github.com/jasmine/jasmine/blob/main/release_notes/5.0.0.md))

**Describe the solution you'd like**
Compatibility with the most current version of Jasmine

**Describe alternatives you've considered**
n/a

**Additional context**
[Current dependency restrictions](https://github.com/hirezio/auto-spies/blob/e433d8d3d012c8c38dfec53b13487214b47322fa/packages/jasmine-auto-spies/package.json#L48C35-L48C35)

Thank you! 🥳

### PR DESCRIPTION
**Pull request by jpgoelz**
updated devDependency and peer dependencies to include latest jasmine version

fix #76

### CODE REVIEW

**Comment by shairez** [comment]
Looks like pnpm lockfile is not committed

Can you please run pnpm locally and commit the lock file?

Thanks

**Comment by jpgoelz** [comment]
Right, fixed that.

**Comment by shairez** [comment]
Thanks @jpgoelz !

**Comment by shairez** [comment]
@all-contributors please add @jpgoelz for maintenance

**Pull request merged**
