### PR TITLE
docs: ✏️ NestJS Testing Module injection example

### PR DESCRIPTION
**Pull request by taylor-ben**
An example for a NestJS Test Bed injection

✅ Closes: #29

### CODE REVIEW

**Comment by shairez** [comment]
Thanks for the contribution @taylor-ben ! 🙏

**2 questions -** 

1. What is "testBest"? 😄 

2. Can you please update the Table of contents with a link to the new section (plus update the same thing in Jasmine-auto-spies' README) ?

Thanks again!

**Comment by taylor-ben** [comment]
> What is "testBest"? 😄
Oops, a typo 😅

> Can you please update the Table of contents with a link to the new section
Sure will

> (plus update the same thing in Jasmine-auto-spies' README) ?
Ok, even though usually NestJS comes with Jest?

**Comment by shairez** [comment]
Thanks!

Oh, so leave it only in `jest-auto-spies` then

Thanks!

**Comment by shairez** [comment]
Hi @taylor-ben 
did you have a chance to add those fixes?

**Comment by shairez** [comment]
closing due to lack of activity

**Pull request closed without merging**
